
# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env        # you’ll create this (don’t commit real secrets)
#     volumes:
#       - .:/app      # optional for live reload (gunicorn won’t reload code)
#     command: gunicorn savannah_project.wsgi:application --bind 0.0.0.0:8000 --workers 2
version: '3.9'

services:
  web:
    build: .
    command: gunicorn savannah_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
