
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env        # you’ll create this (don’t commit real secrets)
    volumes:
      - .:/app      # optional for live reload (gunicorn won’t reload code)
    command: gunicorn savannah_project.wsgi:application --bind 0.0.0.0:8000 --workers 2
