name: Django Docker CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USER }}/myapp
          # Pull latest code
          git pull origin main
          # Build and restart containers
          docker-compose down
          docker-compose build
          docker-compose up -d
          # Optional: run Django migrations
          docker-compose exec web python manage.py migrate
          # Optional: collect static files
          docker-compose exec web python manage.py collectstatic --noinput
